version: "3"

services:
 web:
   image: chgoutham/clusterapp:1.0.0
   deploy:
     replicas:12
     resources:
       limits:
         cpus: "0.1"
         memory: 50M
     restart_policy:
       condition: on-failure
   ports:
     - "80:80"
   network:
     - webnet
network:
  webnet:
